import React, { useState } from 'react';
import { UNIVERSITIES, COURSES } from '../data/universitiesData';
import { DollarSign, Copy, Check, ShieldCheck } from 'lucide-react';
import { useLanguage } from '../lib/LanguageContext';

export const FeeCalculator: React.FC = () => {
  const { t } = useLanguage();
  const [selectedUniId, setSelectedUniId] = useState<string>('emu');
  const [selectedCourseId, setSelectedCourseId] = useState<string>('emu-cs');
  const [scholarshipPercent, setScholarshipPercent] = useState<number>(50);
  const [dormTier, setDormTier] = useState<string>('standard');
  const [includeMealPlan, setIncludeMealPlan] = useState<boolean>(true);
  const [copied, setCopied] = useState<boolean>(false);

  const university = UNIVERSITIES.find((u) => u.id === selectedUniId) || UNIVERSITIES[0];
  const uniCourses = COURSES.filter((c) => c.universityId === selectedUniId);
  const course = COURSES.find((c) => c.id === selectedCourseId) || uniCourses[0] || COURSES[0];

  const baseTuition = course.annualFeeUSD;
  const netTuition = Math.round(baseTuition * (1 - scholarshipPercent / 100));

  let dormFee = 2200;
  if (dormTier === 'economy') dormFee = 1500;
  if (dormTier === 'suite') dormFee = 3500;
  if (dormTier === 'off-campus') dormFee = 0;

  const mealPlanFee = includeMealPlan && dormTier !== 'off-campus' ? 1400 : 0;
  const healthInsurance = 180;
  const registrationAndTax = 320;

  const totalFirstYearUSD = netTuition + dormFee + mealPlanFee + healthInsurance + registrationAndTax;
  const semesterInstallment = Math.round(totalFirstYearUSD / 2);

  const copyQuoteToClipboard = () => {
    const summaryText = `
NORTH CYPRUS UNIVERSITY FEE ESTIMATE QUOTE
==========================================
University: ${university.name} (${university.shortName})
Course: ${course.title}
Base Annual Tuition: $${baseTuition.toLocaleString()} USD
International Scholarship: ${scholarshipPercent}% Waiver
Net Annual Tuition: $${netTuition.toLocaleString()} USD

Accommodation (${dormTier.toUpperCase()}): $${dormFee.toLocaleString()} USD
Meal Plan: $${mealPlanFee.toLocaleString()} USD
Mandatory Health Insurance: $${healthInsurance} USD
Registration & Student Activity Fee: $${registrationAndTax} USD
------------------------------------------
TOTAL ESTIMATED FIRST YEAR INVESTMENT: $${totalFirstYearUSD.toLocaleString()} USD
Semestrial Installment (Pay in 2 parts): $${semesterInstallment.toLocaleString()} USD / semester
==========================================
Generated by North Cyprus Uni Voice AI Advisor
    `.trim();

    navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="space-y-10 py-10">
      {/* Title */}
      <div className="border-b border-white/10 pb-6">
        <span className="text-[10px] font-bold tracking-[0.3em] uppercase text-[#00E5FF] block mb-1">
          {t.calcSubtitle}
        </span>
        <h2 className="text-3xl sm:text-4xl font-display font-bold tracking-tight text-white">
          {t.calcTitle}
        </h2>
        <p className="text-sm text-[#D1D5DB]/80 mt-2 max-w-2xl leading-relaxed">
          {t.calcDesc}
        </p>
      </div>

      <div className="grid lg:grid-cols-12 gap-8 items-start">
        {/* Left Form Column */}
        <div className="lg:col-span-7 glass-panel bg-[#102A43]/80 border border-white/10 rounded-[18px] p-6 sm:p-8 space-y-6">
          <h3 className="text-lg font-display font-bold text-white border-b border-white/10 pb-3 flex items-center gap-2">
            <DollarSign className="w-5 h-5 text-[#00E5FF]" />
            {t.configParamsTitle}
          </h3>

          {/* 1. Select University */}
          <div className="space-y-1.5">
            <label className="text-[10px] uppercase font-bold tracking-widest text-[#D1D5DB]/60">{t.selectUniLabel}</label>
            <select
              value={selectedUniId}
              onChange={(e) => {
                setSelectedUniId(e.target.value);
                const firstCourse = COURSES.find((c) => c.universityId === e.target.value);
                if (firstCourse) setSelectedCourseId(firstCourse.id);
              }}
              className="w-full bg-[#071A2F]/90 border border-white/15 rounded-xl px-3.5 py-3 text-xs text-white focus:outline-none focus:border-[#00E5FF]"
            >
              {UNIVERSITIES.map((u) => (
                <option key={u.id} value={u.id} className="bg-[#071A2F] text-white">
                  {u.name} ({u.shortName}) — {u.city}
                </option>
              ))}
            </select>
          </div>

          {/* 2. Select Course */}
          <div className="space-y-1.5">
            <label className="text-[10px] uppercase font-bold tracking-widest text-[#D1D5DB]/60">{t.selectProgramLabel}</label>
            <select
              value={selectedCourseId}
              onChange={(e) => setSelectedCourseId(e.target.value)}
              className="w-full bg-[#071A2F]/90 border border-white/15 rounded-xl px-3.5 py-3 text-xs text-white focus:outline-none focus:border-[#00E5FF]"
            >
              {uniCourses.map((c) => (
                <option key={c.id} value={c.id} className="bg-[#071A2F] text-white">
                  {c.title} (${c.annualFeeUSD.toLocaleString()}/yr base)
                </option>
              ))}
            </select>
          </div>

          {/* 3. Scholarship Level */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-[10px] uppercase font-bold tracking-widest text-[#D1D5DB]/60">{t.scholarshipTierLabel}</label>
              <span className="text-xs font-bold text-[#00E5FF] uppercase tracking-wider">{scholarshipPercent}% {t.waiverSelectedText}</span>
            </div>
            <div className="grid grid-cols-3 gap-2">
              {[50, 75, 100].map((pct) => (
                <button
                  key={pct}
                  type="button"
                  onClick={() => setScholarshipPercent(pct)}
                  className={`py-3 px-3 text-xs font-bold rounded-xl border transition-all cursor-pointer ${
                    scholarshipPercent === pct
                      ? 'bg-gradient-to-r from-[#00E5FF] to-[#8B5CF6] text-[#071A2F] border-[#00E5FF] shadow-[0_0_15px_rgba(0,229,255,0.4)]'
                      : 'bg-[#071A2F] text-white border-white/15 hover:border-[#00E5FF]'
                  }`}
                >
                  {pct}% Waiver
                  {pct === 50 && <span className="block text-[8px] uppercase tracking-wider font-normal opacity-80">(Standard Automatic)</span>}
                  {pct === 75 && <span className="block text-[8px] uppercase tracking-wider font-normal opacity-80">(High Academic Merit)</span>}
                  {pct === 100 && <span className="block text-[8px] uppercase tracking-wider font-normal opacity-80">(Full Scholarship)</span>}
                </button>
              ))}
            </div>
          </div>

          {/* 4. Dormitory & Housing */}
          <div className="space-y-2">
            <label className="text-[10px] uppercase font-bold tracking-widest text-[#D1D5DB]/60">{t.housingOptionLabel}</label>
            <div className="grid grid-cols-2 gap-2 text-xs">
              {[
                { id: 'economy', label: 'Economy Shared Dorm', fee: '$1,500/yr' },
                { id: 'standard', label: 'Standard En-Suite Dorm', fee: '$2,200/yr' },
                { id: 'suite', label: 'Luxury Studio Suite', fee: '$3,500/yr' },
                { id: 'off-campus', label: 'Private Apartment (Off-Campus)', fee: 'Self-Funded' },
              ].map((tier) => (
                <button
                  key={tier.id}
                  type="button"
                  onClick={() => setDormTier(tier.id)}
                  className={`p-3.5 text-left rounded-xl border transition-all cursor-pointer ${
                    dormTier === tier.id
                      ? 'bg-[#00E5FF]/20 text-[#00E5FF] border-[#00E5FF] shadow-[0_0_15px_rgba(0,229,255,0.2)]'
                      : 'bg-[#071A2F] border-white/15 text-white hover:border-[#00E5FF]/50'
                  }`}
                >
                  <p className="text-xs font-bold">{tier.label}</p>
                  <p className="text-[10px] uppercase tracking-wider opacity-80 mt-0.5">{tier.fee}</p>
                </button>
              ))}
            </div>
          </div>

          {/* 5. Meal Plan Toggle */}
          {dormTier !== 'off-campus' && (
            <div className="flex items-center justify-between p-4 bg-[#071A2F] rounded-xl border border-white/15">
              <div>
                <p className="text-xs font-bold text-white">{t.includeMealPlanText}</p>
                <p className="text-[10px] uppercase tracking-wider text-[#D1D5DB]/60">{t.mealPlanDescText}</p>
              </div>
              <input
                type="checkbox"
                checked={includeMealPlan}
                onChange={(e) => setIncludeMealPlan(e.target.checked)}
                className="w-5 h-5 accent-[#00E5FF] cursor-pointer"
              />
            </div>
          )}
        </div>

        {/* Right Output Summary Quote Column */}
        <div className="lg:col-span-5 glass-panel bg-[#071A2F]/90 text-white border border-[#00E5FF]/30 rounded-[18px] p-6 sm:p-8 space-y-6 shadow-[0_0_40px_rgba(0,229,255,0.15)]">
          <div className="flex items-center justify-between border-b border-white/10 pb-4">
            <div>
              <p className="text-[10px] uppercase tracking-[0.2em] font-bold text-[#00E5FF]">{t.officialEstimateQuote}</p>
              <h3 className="font-display font-bold text-2xl text-white">{university.shortName} Admissions</h3>
            </div>
            <span className="px-3 py-1 text-[9px] font-bold uppercase tracking-widest bg-[#00E5FF]/20 text-[#00E5FF] border border-[#00E5FF]/40 rounded-full">
              {scholarshipPercent}% Waiver
            </span>
          </div>

          {/* Itemized Table */}
          <div className="space-y-3 text-xs">
            <div className="flex items-center justify-between text-[#D1D5DB]/50">
              <span>{t.baseTuitionLabel}</span>
              <span className="line-through">${baseTuition.toLocaleString()} USD</span>
            </div>

            <div className="flex items-center justify-between font-bold text-white pb-2 border-b border-white/10">
              <span>{t.netTuitionLabel} ({scholarshipPercent}% Waiver):</span>
              <span className="text-sm font-display text-[#00E5FF]">${netTuition.toLocaleString()} USD</span>
            </div>

            <div className="flex items-center justify-between text-[#D1D5DB]">
              <span>{t.dormAccomLabel}</span>
              <span>${dormFee.toLocaleString()} USD</span>
            </div>

            {includeMealPlan && dormTier !== 'off-campus' && (
              <div className="flex items-center justify-between text-[#D1D5DB]">
                <span>{t.campusMealPlanLabel}</span>
                <span>${mealPlanFee.toLocaleString()} USD</span>
              </div>
            )}

            <div className="flex items-center justify-between text-[#D1D5DB]">
              <span>{t.healthInsuranceLabel}</span>
              <span>${healthInsurance} USD</span>
            </div>

            <div className="flex items-center justify-between text-[#D1D5DB]">
              <span>{t.registrationFeeLabel}</span>
              <span>${registrationAndTax} USD</span>
            </div>
          </div>

          {/* Total Highlight Box */}
          <div className="bg-[#102A43] text-white p-5 space-y-2 border border-[#00E5FF]/30 rounded-2xl shadow-inner">
            <div className="flex items-center justify-between">
              <span className="text-[10px] uppercase font-bold tracking-widest text-[#D1D5DB]/60">{t.totalFirstYearLabel}</span>
              <span className="text-2xl font-display font-black text-[#7CFC00]">${totalFirstYearUSD.toLocaleString()} USD</span>
            </div>

            <div className="flex items-center justify-between text-xs pt-2 border-t border-white/10 text-[#D1D5DB]">
              <span>{t.semesterScheduleLabel}</span>
              <span className="font-bold text-white">${semesterInstallment.toLocaleString()} / semester</span>
            </div>
          </div>

          {/* Payment Guidance */}
          <div className="space-y-1.5 text-[11px] text-[#D1D5DB]/70 pt-2 border-t border-white/10">
            <p className="flex items-center gap-1.5 text-[#7CFC00] font-semibold">
              <ShieldCheck className="w-4 h-4 text-[#7CFC00]" />
              {t.directPaymentText}
            </p>
            <p>• {t.semesterScheduleLabel}</p>
            <p>• {t.tuitionLockedText} ({course.durationYears} {t.yearsDurationText}).</p>
          </div>

          {/* Buttons */}
          <button
            onClick={copyQuoteToClipboard}
            className="btn-cta-coral w-full flex items-center justify-center space-x-2 py-3.5 px-4 text-[10px] uppercase font-bold tracking-widest cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-white" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? t.quoteCopiedMsg : t.copyQuoteBtn}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
